AWSTemplateFormatVersion: 2010-09-09

Parameters:
  RepositoryName:
    Type: String
    Description: Enter the CodeCommit repository name to source for replication.

  BranchName:
    Type: String
    Description: Enter the branch name of repository.

Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !Join [':', ['arn:aws:iam:', !Ref 'AWS::AccountId', 'role/labs-codepipeline']]
      ArtifactStore:
        Type: S3
        Location: !Join ['-', ['codepipeline', !Ref 'AWS::Region', !Ref 'AWS::AccountId']]
      Stages:
        - Name: Source
          Actions:
            - Name: CloneRepo
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              Configuration:
                BranchName: !Ref BranchName
                RepositoryName: !Ref RepositoryName
              OutputArtifacts:
                - Name: SourceOutput
              RunOrder: 1