AWSTemplateFormatVersion: 2010-09-09

Parameters:
  RepositoryName:
    Type: String
    Description: Enter the CodeCommit repository name to source for replication.

  BranchName:
    Type: String
    Description: Enter the branch name of repository.

Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Join ['-', [!Ref RepositoryName, !Ref BranchName]]
      RoleArn: !Join [':', ['arn:aws:iam:', !Ref 'AWS::AccountId', 'role/labs-codepipeline']]
      ArtifactStore:
        Type: S3
        Location: !Join ['-', ['codepipeline', !Ref 'AWS::Region', !Ref 'AWS::AccountId']]
      Stages:
        - Name: Source
          Actions:
            - Name: CloneRepo
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              Configuration:
                BranchName: !Ref BranchName
                RepositoryName: !Ref RepositoryName
              OutputArtifacts:
                - Name: SourceOutput
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
              - Name: BuildResult
              Configuration:
                PrimarySource: SourceOutput
                ProjectName: !Ref MyCodeBuild
              RunOrder: 1

  MyCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Join ['-', ['Build', !Ref RepositoryName, !Ref BranchName]]
      Description: CodeBuild Project
      ServiceRole: !Join [':', ['arn:aws:iam:', !Ref 'AWS::AccountId', 'role/labs-codepipeline']]
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: scripts/buildspec.yml
      TimeoutInMinutes: 10
      Tags:
      - Key: Name
        Value:
          Fn::Sub: ${AWS::StackName}-my-project
